/* finvirt5.c - Makes FINMGT REVENUE 1 Virtual Fields */
#include <cstdio>





#include <rptgen.hpp>
/*ADDLIB rpt */
/*ADDLIB mix */
/*ADDLIB olh */
/*ADDLIB sec */
/*ADDLIB trans */
/*ADDLIB gui */
/*ADDLIB nrd */
/*ADDLIB misc */
/*ADDLIB ctpf */

void FINMGTCreateRV1()
{
	DFvirtual *d=NULL;
	DFincvir *i;
	char temp[15000];
	char revenuepos=FALSE;
	char *libx=NULL;
	RDAGenericSetup *gsv=NULL;

	libx=Rmalloc(RDAstrlen(CURRENTDIRECTORY)+RDAstrlen("FINMGT")+11);
#ifndef WIN32
	sprintf(libx,"%s/rda/%s.GSV",CURRENTDIRECTORY,"FINMGT");
#endif
#ifdef WIN32
	sprintf(libx,"%s\\rda\\%s.GSV",CURRENTDIRECTORY,"FINMGT");
#endif

	gsv=RDAGenericSetupNew("FINMGT","USE REVENUE POS");
	if(gsv!=NULL)
	{
		if(!getRDAGenericSetupbin(libx,gsv))
		{
			revenuepos=*gsv->value.string_value;
		} else {
			revenuepos=FALSE;
		}
	}
	if(gsv!=NULL) FreeRDAGenericSetup(gsv);
	if(libx!=NULL) Rfree(libx);

	if(revenuepos)
	{
	d=DFvirtualNEW("FINMGT","ANNUAL POSTED REVENUE POS");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR REVENUE POS]",
		"[FINMGT][FINRYR][JANUARY REVENUE POS]",
		"[FINMGT][FINRYR][FEBRUARY REVENUE POS]",
		"[FINMGT][FINRYR][MARCH REVENUE POS]",
		"[FINMGT][FINRYR][APRIL REVENUE POS]",
		"[FINMGT][FINRYR][MAY REVENUE POS]",
		"[FINMGT][FINRYR][JUNE REVENUE POS]",
		"[FINMGT][FINRYR][JULY REVENUE POS]",
		"[FINMGT][FINRYR][AUGUST REVENUE POS]",
		"[FINMGT][FINRYR][SEPTEMBER REVENUE POS]",
		"[FINMGT][FINRYR][OCTOBER REVENUE POS]",
		"[FINMGT][FINRYR][NOVEMBER REVENUE POS]",
		"[FINMGT][FINRYR][DECEMBER REVENUE POS]",
		"[FINMGT][FINRYR][POST YEAR REVENUE POS]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual posted revenue, i.e. the total posted Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL DISTRIBUTED REVENUE POS");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][JANUARY DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][FEBRUARY DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][MARCH DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][APRIL DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][MAY DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][JUNE DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][JULY DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][AUGUST DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][SEPTEMBER DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][OCTOBER DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][NOVEMBER DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][DECEMBER DISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][POST YEAR DISTRIBUTED REVENUE POS]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual distributed revenue, i.e. the total distributed Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL UNDISTRIBUTED REVENUE POS");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][JANUARY UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][FEBRUARY UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][MARCH UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][APRIL UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][MAY UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][JUNE UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][JULY UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][AUGUST UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][SEPTEMBER UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][OCTOBER UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][NOVEMBER UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][DECEMBER UNDISTRIBUTED REVENUE POS]",
		"[FINMGT][FINRYR][POST YEAR UNDISTRIBUTED REVENUE POS]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual undistributed revenue, i.e. the total undistributed Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	}
	d=DFvirtualNEW("FINMGT","ANNUAL POSTED ESTIMATED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JANUARY ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][FEBRUARY ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][MARCH ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][APRIL ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][MAY ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JUNE ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JULY ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][AUGUST ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][SEPTEMBER ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][OCTOBER ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][NOVEMBER ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][DECEMBER ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][POST YEAR ESTIMATED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual posted estimated revenue, i.e. the total posted Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL DISTRIBUTED ESTIMATED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JANUARY DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][FEBRUARY DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][MARCH DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][APRIL DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][MAY DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JUNE DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JULY DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][AUGUST DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][SEPTEMBER DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][OCTOBER DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][NOVEMBER DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][DECEMBER DISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][POST YEAR DISTRIBUTED ESTIMATED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual distributed estimated revenue, i.e. the total distributed Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL UNDISTRIBUTED ESTIMATED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JANUARY UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][FEBRUARY UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][MARCH UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][APRIL UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][MAY UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JUNE UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][JULY UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][AUGUST UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][SEPTEMBER UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][OCTOBER UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][NOVEMBER UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][DECEMBER UNDISTRIBUTED ESTIMATED REVENUE]",
		"[FINMGT][FINRYR][POST YEAR UNDISTRIBUTED ESTIMATED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual undistributed estimated revenue, i.e. the total undistributed Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL POSTED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR REVENUE]",
		"[FINMGT][FINRYR][JANUARY REVENUE]",
		"[FINMGT][FINRYR][FEBRUARY REVENUE]",
		"[FINMGT][FINRYR][MARCH REVENUE]",
		"[FINMGT][FINRYR][APRIL REVENUE]",
		"[FINMGT][FINRYR][MAY REVENUE]",
		"[FINMGT][FINRYR][JUNE REVENUE]",
		"[FINMGT][FINRYR][JULY REVENUE]",
		"[FINMGT][FINRYR][AUGUST REVENUE]",
		"[FINMGT][FINRYR][SEPTEMBER REVENUE]",
		"[FINMGT][FINRYR][OCTOBER REVENUE]",
		"[FINMGT][FINRYR][NOVEMBER REVENUE]",
		"[FINMGT][FINRYR][DECEMBER REVENUE]",
		"[FINMGT][FINRYR][POST YEAR REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual posted revenue, i.e. the total posted Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL DISTRIBUTED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][JANUARY DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][FEBRUARY DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][MARCH DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][APRIL DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][MAY DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][JUNE DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][JULY DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][AUGUST DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][SEPTEMBER DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][OCTOBER DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][NOVEMBER DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][DECEMBER DISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][POST YEAR DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual distributed revenue, i.e. the total distributed Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL UNDISTRIBUTED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s+%s",
		"[FINMGT][FINRYR][PRE-YEAR UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][JANUARY UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][FEBRUARY UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][MARCH UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][APRIL UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][MAY UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][JUNE UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][JULY UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][AUGUST UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][SEPTEMBER UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][OCTOBER UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][NOVEMBER UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][DECEMBER UNDISTRIBUTED REVENUE]",
		"[FINMGT][FINRYR][POST YEAR UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual undistributed revenue, i.e. the total undistributed Previous Year, January, February, March, April, May, June, July, August, September, October, November, December, and Post Year.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL ESTIMATED REVENUE TOTAL]-[ANNUAL REVENUE TOTAL]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual unrealized revenue which is calculated by the difference of the posted, distributed, and undistributed estimated revenue and the posted, distributed, and undistributed revenue amounts");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL POSTED ESTIMATED REVENUE]-[ANNUAL POSTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual revenue which is calculated by the sum of the posted, distributed, and undistributed revenue amounts");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL DISTRIBUTED ESTIMATED REVENUE]-[ANNUAL DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual revenue which is calculated by the sum of the posted, distributed, and undistributed revenue amounts");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL UNDISTRIBUTED ESTIMATED REVENUE]-[ANNUAL UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual revenue which is calculated by the sum of the posted, distributed, and undistributed revenue amounts");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL POSTED REVENUE]+[ANNUAL DISTRIBUTED REVENUE]+[ANNUAL UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual revenue which is calculated by the sum of the posted, distributed, and undistributed revenue amounts");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL ESTIMATED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL POSTED ESTIMATED REVENUE]+[ANNUAL DISTRIBUTED ESTIMATED REVENUE]+[ANNUAL UNDISTRIBUTED ESTIMATED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual estimated revenue, i.e. the total posted estimated revenue, distributed estimated revenue, and undistributed estimated revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL POSTED ESTIMATED REVENUE]-[ANNUAL POSTED REVENUE]-[ANNUAL DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual unrealized distributed revenue which is calculated by the difference of the annual posted estimated revenue and the annual posted and distributed revenue amounts");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","ANNUAL UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[ANNUAL POSTED ESTIMATED REVENUE]-[ANNUAL POSTED REVENUE]-[ANNUAL DISTRIBUTED REVENUE]-[ANNUAL UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the total annual unrealized undistributed revenue which is calculated by the difference of the annual posted estimated revenue and the annual posted, distributed, and undistributed revenue amounts");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","PRE-YEAR POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][PRE-YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][PRE-YEAR REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Pre-Year posted unrealized revenue which is calculated by the difference between the Pre-Year posted estimated and the Pre-Year posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","POST YEAR POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][POST YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][POST YEAR REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Post Year posted unrealized revenue which is calculated by the difference between the Post Year posted estimated revenue and the Post Year posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JANUARY POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JANUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][JANUARY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the January posted unrealized revenue which is calculated by the difference between the January posted estimated revenue and the January posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","FEBRUARY POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][FEBRUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][FEBRUARY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the February posted unrealized revenue which is calculated by the difference between the February posted estimated revenue and the February posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MARCH POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MARCH ESTIMATED REVENUE]-[FINMGT][FINRYR][MARCH REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the March posted unrealized revenue which is calculated by the difference between the March posted estimated revenue and the March posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","APRIL POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][APRIL ESTIMATED REVENUE]-[FINMGT][FINRYR][APRIL REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the April posted unrealized revenue which is calculated by the difference between the April posted estimated revenue and the April posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MAY POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MAY ESTIMATED REVENUE]-[FINMGT][FINRYR][MAY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the May posted unrealized revenue which is calculated by the difference between the May posted estimated revenue and the May posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JUNE POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JUNE ESTIMATED REVENUE]-[FINMGT][FINRYR][JUNE REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the June posted unrealized revenue which is calculated by the difference between the June posted estimated revenue and the June posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JULY POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JULY ESTIMATED REVENUE]-[FINMGT][FINRYR][JULY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the July posted unrealized revenue which is calculated by the difference between the July posted estimated revenue and the July posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","AUGUST POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][AUGUST ESTIMATED REVENUE]-[FINMGT][FINRYR][AUGUST REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the August posted unrealized revenue which is calculated by the difference between the August posted estimated revenue and the August posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","SEPTEMBER POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][SEPTEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][SEPTEMBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the September posted unrealized revenue which is calculated by the difference between the September posted estimated revenue sum of the September posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","OCTOBER POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][OCTOBER ESTIMATED REVENUE]-[FINMGT][FINRYR][OCTOBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the October posted unrealized revenue which is calculated by the difference between the October posted estimated revenue and the sum of the October posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","NOVEMBER POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][NOVEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][NOVEMBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the November posted unrealized revenue which is calculated by the difference between the November posted estimated revenue and the November posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","DECEMBER POSTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][DECEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][DECEMBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the December posted unrealized revenue which is calculated by the difference between the December posted estimated revenue and the sum of the December posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","PRE-YEAR DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][PRE-YEAR DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][PRE-YEAR DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Pre-Year distributed unrealized revenue which is calculated by the difference between the Pre-Year distributed estimated revenue and the Pre-Year distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","POST YEAR DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][POST YEAR DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][POST YEAR DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Post Year distributed unrealized revenue which is calculated by the difference between the Post Year distributed estimated revenue and the Post Year distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JANUARY DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JANUARY DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][JANUARY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the January distributed unrealized revenue which is calculated by the difference between the January distributed estimated revenue and the January distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","FEBRUARY DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][FEBRUARY DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][FEBRUARY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the February distributed unrealized revenue which is calculated by the difference between the February distributed estimated revenue and the February distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MARCH DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MARCH DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][MARCH DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the March distributed unrealized revenue which is calculated by the difference between the March distributed estimated revenue and the March distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","APRIL DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][APRIL DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][APRIL DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the April distributed unrealized revenue which is calculated by the difference between the April distributed estimated revenue and the April distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MAY DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MAY DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][MAY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the May distributed unrealized revenue which is calculated by the difference between the May distributed estimated revenue and the May distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JUNE DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JUNE DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][JUNE DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the June distributed unrealized revenue which is calculated by the difference between the June distributed estimated revenue and the June distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JULY DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JULY DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][JULY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the July distributed unrealized revenue which is calculated by the difference between the July distributed estimated revenue and the sum of the July distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","AUGUST DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][AUGUST DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][AUGUST DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the August distributed unrealized revenue which is calculated by the difference between the August distributed estimated revenue and the sum of the August distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","SEPTEMBER DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][SEPTEMBER DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][SEPTEMBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the September distributed unrealized revenue which is calculated by the difference between the September distributed estimated revenue and the September distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","OCTOBER DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][OCTOBER DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][OCTOBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the October distributed unrealized revenue which is calculated by the difference between the October distributed estimated revenue and the sum of the October distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","NOVEMBER DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][NOVEMBER DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][NOVEMBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the November distributed unrealized revenue which is calculated by the difference between the November distributed estimated revenue and the November distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","DECEMBER DISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][DECEMBER DISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][DECEMBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the December distributed unrealized revenue which is calculated by the difference between the December distributed estimated revenue and the December distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","PRE-YEAR UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][PRE-YEAR UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][PRE-YEAR UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Pre-Year undistributed unrealized revenue which is calculated by the difference between the Pre-Year undistributed estimated revenue and the Pre-Year undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","POST YEAR UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][POST YEAR UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][POST YEAR UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Post Year undistributed unrealized revenue which is calculated by the difference between the Post Year undistributed estimated revenue and the Post Year undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JANUARY UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JANUARY UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][JANUARY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the January undistributed unrealized revenue which is calculated by the difference between the January undistributed estimated revenue and the January undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","FEBRUARY UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][FEBRUARY UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][FEBRUARY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the February undistributed unrealized revenue which is calculated by the difference between the February undistributed estimated revenue and the February undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MARCH UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MARCH UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][MARCH UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the March undistributed unrealized revenue which is calculated by the difference between the March undistributed estimated revenue and the March undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","APRIL UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][APRIL UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][APRIL UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the April undistributed unrealized revenue which is calculated by the difference between the April undistributed estimated revenue and the April undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MAY UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MAY UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][MAY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the May undistributed unrealized revenue which is calculated by the difference between the May undistributed estimated revenue and the May undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JUNE UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JUNE UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][JUNE UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the June undistributed unrealized revenue which is calculated by the difference between the June undistributed estimated revenue and the June undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JULY UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JULY UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][JULY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the July undistributed unrealized revenue which is calculated by the difference between the July undistributed estimated revenue and the July undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","AUGUST UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][AUGUST UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][AUGUST UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the August undistributed unrealized revenue which is calculated by the difference between the August undistributed estimated revenue and the August undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","SEPTEMBER UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][SEPTEMBER UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][SEPTEMBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the September undistributed unrealized revenue which is calculated by the difference between the September undistributed estimated revenue and the September undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","OCTOBER UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][OCTOBER UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][OCTOBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the October undistributed unrealized revenue which is calculated by the difference between the October undistributed estimated revenue and the October undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","NOVEMBER UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][NOVEMBER UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][NOVEMBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the November undistributed unrealized revenue which is calculated by the difference between the November undistributed estimated revenue and the November undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","DECEMBER UNDISTRIBUTED UNREALIZED REVENUE");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][DECEMBER UNDISTRIBUTED ESTIMATED REVENUE]-[FINMGT][FINRYR][DECEMBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the December undistributed unrealized revenue which is calculated by the difference between the December undistributed estimated revenue and the December undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","PRE-YEAR POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][PRE-YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][PRE-YEAR REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Pre-Year posted unrealized revenue total which is calculated by the difference between the Pre-Year posted estimated revenue and the Pre-Year posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","POST YEAR POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][POST YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][POST YEAR REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Post Year posted unrealized revenue total which is calculated by the difference between the Post Year posted estimated revenue and the Post Year posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JANUARY POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JANUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][JANUARY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the January posted unrealized revenue total which is calculated by the difference between the January posted estimated revenue and the January posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","FEBRUARY POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][FEBRUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][FEBRUARY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the February posted unrealized revenue total which is calculated by the difference between the February posted estimated revenue and the February posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MARCH POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MARCH ESTIMATED REVENUE]-[FINMGT][FINRYR][MARCH REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the March posted unrealized revenue total which is calculated by the difference between the March posted estimated revenue and the March posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","APRIL POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][APRIL ESTIMATED REVENUE]-[FINMGT][FINRYR][APRIL REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the April posted unrealized revenue total which is calculated by the difference between the April posted estimated revenue and the April posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MAY POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MAY ESTIMATED REVENUE]-[FINMGT][FINRYR][MAY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the May posted unrealized revenue total which is calculated by the difference between the May posted estimated revenue and the May posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JUNE POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JUNE ESTIMATED REVENUE]-[FINMGT][FINRYR][JUNE REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the June posted unrealized revenue total which is calculated by the difference between the June posted estimated revenue and the June posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JULY POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JULY ESTIMATED REVENUE]-[FINMGT][FINRYR][JULY REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the July posted unrealized revenue total which is calculated by the difference between the July posted estimated revenue and the July posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","AUGUST POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][AUGUST ESTIMATED REVENUE]-[FINMGT][FINRYR][AUGUST REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the August posted unrealized revenue total which is calculated by the difference between the August posted estimated revenue and the August posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","SEPTEMBER POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][SEPTEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][SEPTEMBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the September posted unrealized revenue total which is calculated by the difference between the September posted estimated revenue and the September posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","OCTOBER POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][OCTOBER ESTIMATED REVENUE]-[FINMGT][FINRYR][OCTOBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the October posted unrealized revenue total which is calculated by the difference between the October posted estimated revenue and the October posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","NOVEMBER POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][NOVEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][NOVEMBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the November posted unrealized revenue total which is calculated by the difference between the November posted estimated revenue and the November posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","DECEMBER POSTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][DECEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][DECEMBER REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the December posted unrealized revenue total which is calculated by the difference between the December posted estimated revenue and the December posted revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","PRE-YEAR DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][PRE-YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][PRE-YEAR REVENUE]-[FINMGT][FINRYR][PRE-YEAR DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Pre-Year distributed unrealized revenue total which is calculated by the difference between the Pre-Year posted estimated revenue and the sum of the Pre-Year posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","POST YEAR DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][POST YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][POST YEAR REVENUE]-[FINMGT][FINRYR][POST YEAR DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Post Year distributed unrealized revenue total which is calculated by the difference between the Post Year posted estimated revenue and the sum of the Post Year posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JANUARY DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JANUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][JANUARY REVENUE]-[FINMGT][FINRYR][JANUARY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the January distributed unrealized revenue total which is calculated by the difference between the January posted estimated revenue and the sum of the January posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","FEBRUARY DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][FEBRUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][FEBRUARY REVENUE]-[FINMGT][FINRYR][FEBRUARY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the February distributed unrealized revenue total which is calculated by the difference between the February posted estimated revenue and the sum of the February posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MARCH DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MARCH ESTIMATED REVENUE]-[FINMGT][FINRYR][MARCH REVENUE]-[FINMGT][FINRYR][MARCH DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the March distributed unrealized revenue total which is calculated by the difference between the March posted estimated revenue and the sum of the March posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","APRIL DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][APRIL ESTIMATED REVENUE]-[FINMGT][FINRYR][APRIL REVENUE]-[FINMGT][FINRYR][APRIL DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the April distributed unrealized revenue total which is calculated by the difference between the April posted estimated revenue and the sum of the April posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MAY DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MAY ESTIMATED REVENUE]-[FINMGT][FINRYR][MAY REVENUE]-[FINMGT][FINRYR][MAY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the May distributed unrealized revenue total which is calculated by the difference between the May posted estimated revenue and the sum of the May posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JUNE DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JUNE ESTIMATED REVENUE]-[FINMGT][FINRYR][JUNE REVENUE]-[FINMGT][FINRYR][JUNE DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the June distributed unrealized revenue total which is calculated by the difference between the June posted estimated revenue and the sum of the June posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JULY DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JULY ESTIMATED REVENUE]-[FINMGT][FINRYR][JULY REVENUE]-[FINMGT][FINRYR][JULY DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the July distributed unrealized revenue total which is calculated by the difference between the July posted estimated revenue and the sum of the July posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","AUGUST DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][AUGUST ESTIMATED REVENUE]-[FINMGT][FINRYR][AUGUST REVENUE]-[FINMGT][FINRYR][AUGUST DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the August distributed unrealized revenue total which is calculated by the difference between the August posted estimated revenue and the sum of the August posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","SEPTEMBER DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][SEPTEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][SEPTEMBER REVENUE]-[FINMGT][FINRYR][SEPTEMBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the September distributed unrealized revenue total which is calculated by the difference between the September posted estimated revenue and the sum of the September posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","OCTOBER DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][OCTOBER ESTIMATED REVENUE]-[FINMGT][FINRYR][OCTOBER REVENUE]-[FINMGT][FINRYR][OCTOBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the October distributed unrealized revenue total which is calculated by the difference between the October posted estimated revenue and the sum of the October posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","NOVEMBER DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][NOVEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][NOVEMBER REVENUE]-[FINMGT][FINRYR][NOVEMBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the November distributed unrealized revenue total which is calculated by the difference between the November posted estimated revenue and the sum of the November posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","DECEMBER DISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][DECEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][DECEMBER REVENUE]-[FINMGT][FINRYR][DECEMBER DISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the December distributed unrealized revenue total which is calculated by the difference between the December posted estimated revenue and the sum of the December posted and distributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","PRE-YEAR UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][PRE-YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][PRE-YEAR REVENUE]-[FINMGT][FINRYR][PRE-YEAR DISTRIBUTED REVENUE]-[FINMGT][FINRYR][PRE-YEAR UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Pre-Year undistributed unrealized revenue total which is calculated by the difference between the Pre-Year posted estimated revenue and the sum of the Pre-Year posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","POST YEAR UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][POST YEAR ESTIMATED REVENUE]-[FINMGT][FINRYR][POST YEAR REVENUE]-[FINMGT][FINRYR][POST YEAR DISTRIBUTED REVENUE]-[FINMGT][FINRYR][POST YEAR UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the Post Year undistributed unrealized revenue total which is calculated by the difference between the Post Year posted estimated revenue and the sum of the Post Year posted, distributed, and undistributed revenue.")
;
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JANUARY UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JANUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][JANUARY REVENUE]-[FINMGT][FINRYR][JANUARY DISTRIBUTED REVENUE]-[FINMGT][FINRYR][JANUARY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the January undistributed unrealized revenue total which is calculated by the difference between the January posted estimated revenue and the sum of the January posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","FEBRUARY UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][FEBRUARY ESTIMATED REVENUE]-[FINMGT][FINRYR][FEBRUARY REVENUE]-[FINMGT][FINRYR][FEBRUARY DISTRIBUTED REVENUE]-[FINMGT][FINRYR][FEBRUARY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the February undistributed unrealized revenue total which is calculated by the difference between the February posted estimated revenue and the sum of the February posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MARCH UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MARCH ESTIMATED REVENUE]-[FINMGT][FINRYR][MARCH REVENUE]-[FINMGT][FINRYR][MARCH DISTRIBUTED REVENUE]-[FINMGT][FINRYR][MARCH UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the March undistributed unrealized revenue total which is calculated by the difference between the March posted estimated revenue and the sum of the March posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","APRIL UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][APRIL ESTIMATED REVENUE]-[FINMGT][FINRYR][APRIL REVENUE]-[FINMGT][FINRYR][APRIL DISTRIBUTED REVENUE]-[FINMGT][FINRYR][APRIL UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the April undistributed unrealized revenue total which is calculated by the difference between the April posted estimated revenue and the sum of the April posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","MAY UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][MAY ESTIMATED REVENUE]-[FINMGT][FINRYR][MAY REVENUE]-[FINMGT][FINRYR][MAY DISTRIBUTED REVENUE]-[FINMGT][FINRYR][MAY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the May undistributed unrealized revenue total which is calculated by the difference between the May posted estimated revenue and the sum of the May posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JUNE UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JUNE ESTIMATED REVENUE]-[FINMGT][FINRYR][JUNE REVENUE]-[FINMGT][FINRYR][JUNE DISTRIBUTED REVENUE]-[FINMGT][FINRYR][JUNE UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the June undistributed unrealized revenue total which is calculated by the difference between the June posted estimated revenue and the sum of the June posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","JULY UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][JULY ESTIMATED REVENUE]-[FINMGT][FINRYR][JULY REVENUE]-[FINMGT][FINRYR][JULY DISTRIBUTED REVENUE]-[FINMGT][FINRYR][JULY UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the July undistributed unrealized revenue total which is calculated by the difference between the July posted estimated revenue and the sum of the July posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","AUGUST UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][AUGUST ESTIMATED REVENUE]-[FINMGT][FINRYR][AUGUST REVENUE]-[FINMGT][FINRYR][AUGUST DISTRIBUTED REVENUE]-[FINMGT][FINRYR][AUGUST UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the August undistributed unrealized revenue total which is calculated by the difference between the August posted estimated revenue and the sum of the August posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","SEPTEMBER UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][SEPTEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][SEPTEMBER REVENUE]-[FINMGT][FINRYR][SEPTEMBER DISTRIBUTED REVENUE]-[FINMGT][FINRYR][SEPTEMBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the September undistributed unrealized revenue total which is calculated by the difference between the September posted estimated revenue and the sum of the September posted, distributed, and undistributed revenue.")
;
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","OCTOBER UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][OCTOBER ESTIMATED REVENUE]-[FINMGT][FINRYR][OCTOBER REVENUE]-[FINMGT][FINRYR][OCTOBER DISTRIBUTED REVENUE]-[FINMGT][FINRYR][OCTOBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the October undistributed unrealized revenue total which is calculated by the difference between the October posted estimated revenue and the sum of the October posted, distrbuted, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","NOVEMBER UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][NOVEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][NOVEMBER REVENUE]-[FINMGT][FINRYR][NOVEMBER DISTRIBUTED REVENUE]-[FINMGT][FINRYR][NOVEMBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the November undistributed unrealized revenue total which is calculated by the difference between the November posted estimated revenue and the sum of the November posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
	d=DFvirtualNEW("FINMGT","DECEMBER UNDISTRIBUTED UNREALIZED REVENUE TOTAL");
	d->incvir=Rmalloc(sizeof(DFincvir));
	i=d->incvir;
	i->module=stralloc("FINMGT");
	i->file=stralloc("FINRYR");
	d->vtype=0;
	d->num=1;
	d->type=DOLLARS;
	d->length=20;
	d->when=0;
	d->avail2rsrc=TRUE;
	memset(temp,0,15000);
	sprintf(temp,"[FINMGT][FINRYR][DECEMBER ESTIMATED REVENUE]-[FINMGT][FINRYR][DECEMBER REVENUE]-[FINMGT][FINRYR][DECEMBER DISTRIBUTED REVENUE]-[FINMGT][FINRYR][DECEMBER UNDISTRIBUTED REVENUE]");
	d->expression=stralloc(temp);
	memset(temp,0,15000);
	sprintf(temp,"This virtual field represents the December undistributed unrealized revenue total which is calculated by the difference between the December posted estimated revenue and the sum of the December posted, distributed, and undistributed revenue.");
	d->desc=stralloc(temp);
	memset(temp,0,15000);
	writeDFvirtual("FINMGT",d);
	if(d!=NULL) FreeDFvirtual(d);
}
