		fprintf(fp,"CheckString()\n");
		fprintf(fp,"{\n");
		fprintf(fp,"	if [ $(echo $1 | cut -c\"$START_NUMBER\"'-'\"$CUT_NUMBER\") == \":\" 2>/dev/null ]\n");
		fprintf(fp,"	then\n");
		fprintf(fp,"	#	echo \"test true\"\n");
		fprintf(fp,"		LOOP_FINISHED=1\n");
		fprintf(fp,"	else\n");
		fprintf(fp,"		START_NUMBER=`expr $START_NUMBER + 1`\n");
		fprintf(fp,"		CUT_NUMBER=`expr $CUT_NUMBER + 1`\n");
		fprintf(fp,"	fi\n");
		fprintf(fp,"	#echo \"\"	\n");
		fprintf(fp,"	#echo \"START_NUMBER=$START_NUMBER\"	\n");
		fprintf(fp,"	#echo \"CUT_NUMBER=$CUT_NUMBER\"	\n");
		fprintf(fp,"}\n");
		fprintf(fp,"\n");
		fprintf(fp,"\n");
		fprintf(fp,"for xxx in `echo $DISPLAY | awk '{print $1}'`\n");
		fprintf(fp,"do\n");
		fprintf(fp,"	TEST1=0\n");
		fprintf(fp,"	TEST2=0\n");
		fprintf(fp,"	TEST3=0\n");
		fprintf(fp,"	if [ $(echo $xxx | cut -c0-1) == \":\" ]\n");
		fprintf(fp,"	then\n");
		fprintf(fp,"		if [ $(echo $xxx | cut -c3-3) == \".\" ]\n");
		fprintf(fp,"		then\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c2-2`\n");
		fprintf(fp,"		else\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c2-3`\n");
		fprintf(fp,"		fi\n");
		fprintf(fp,"	else	\n");
		fprintf(fp,"		TEST1=1\n");
		fprintf(fp,"	#	echo TEST1=1\n");
		fprintf(fp,"	fi\n");
		fprintf(fp,"	\n");
		fprintf(fp,"	if [ $(echo $xxx | cut -c0-9) == \"127.0.0.1\" ]\n");
		fprintf(fp,"	then\n");
		fprintf(fp,"		if [ $(echo $xxx | cut -c12-12) == \".\" ]\n");
		fprintf(fp,"		then\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c11-11`\n");
		fprintf(fp,"		else\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c11-12`\n");
		fprintf(fp,"		fi\n");
		fprintf(fp,"	else	\n");
		fprintf(fp,"		TEST2=1\n");
		fprintf(fp,"	#	echo TEST2=1\n");
		fprintf(fp,"	fi\n");
		fprintf(fp,"	\n");
		fprintf(fp,"	if [ $(echo $xxx | cut -c0-9) == \"localhost\" ]\n");
		fprintf(fp,"	then\n");
		fprintf(fp,"		if [ $(echo $xxx | cut -c12-12) == \".\" ]\n");
		fprintf(fp,"		then\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c11-11`\n");
		fprintf(fp,"		else\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c11-12`\n");
		fprintf(fp,"		fi\n");
		fprintf(fp,"	else	\n");
		fprintf(fp,"		TEST3=1\n");
		fprintf(fp,"	#	echo TEST3=1\n");
		fprintf(fp,"	fi\n");
		fprintf(fp,"\n");
		fprintf(fp,"	if [ $TEST1 == 1 -a $TEST2 == 1 -a $TEST3 == 1 ]\n");
		fprintf(fp,"	then\n");
		fprintf(fp,"	#	echo \"TEST4=TRUE\"\n");
		fprintf(fp,"\n");
		fprintf(fp,"		START_NUMBER=0\n");
		fprintf(fp,"		CUT_NUMBER=0\n");
		fprintf(fp,"		LOOP_FINISHED=0\n");
		fprintf(fp,"		\n");
		fprintf(fp,"		until [ $LOOP_FINISHED == 1 ]\n");
		fprintf(fp,"		do\n");
		fprintf(fp,"			CheckString $DISPLAY\n");
		fprintf(fp,"		done	\n");
		fprintf(fp,"		\n");
		fprintf(fp,"	#	echo \"START_NUMBER=$START_NUMBER\"	\n");
		fprintf(fp,"	#	echo \"CUT_NUMBER=$CUT_NUMBER\"	\n");
		fprintf(fp,"		\n");
		fprintf(fp,"		VNC_START=`expr $CUT_NUMBER + 1`\n");
		fprintf(fp,"		VNC_CUT=`expr $CUT_NUMBER + 2`\n");
		fprintf(fp,"\n");
		fprintf(fp,"	#	echo VNC_START=$VNC_START\n");
		fprintf(fp,"	#	echo VNC_CUT=$VNC_CUT\n");
		fprintf(fp,"\n");
		fprintf(fp,"		if [ $(echo $xxx | cut -c\"$VNC_CUT\"'-'\"$VNC_CUT\") == \".\" ]\n");
		fprintf(fp,"		then	\n");
		fprintf(fp,"		#	echo \"TEST4-1=TRUE\"\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c\"$VNC_START\"'-'\"$VNC_START\"`\n");
		fprintf(fp,"		else\n");
		fprintf(fp,"		#	echo \"TEST4-2=TRUE\"\n");
		fprintf(fp,"			VNC_NUMBER=`echo $xxx | cut -c\"$VNC_START\"'-'\"$VNC_CUT\"`\n");
		fprintf(fp,"		fi\n");
		fprintf(fp,"		\n");
		fprintf(fp,"	fi\n");
		fprintf(fp,"	\n");
		fprintf(fp,"	echo \"VNC_NUMBER=$VNC_NUMBER\"	\n");
		fprintf(fp,"\n");
		fprintf(fp,"	vncconnect -display 127.0.0.1:$VNC_NUMBER support-srv.rdasys.com:55$1\n");
		fprintf(fp,"done\n");
