/*lint -library */
/*LIBRARY to contain functions mixed with nrd & gui calls */
/*CPP_OPART IBM390lib */
/*CPP_OPART passkey */
/*CPP_OPART optscrn */
/*CPP_OPART rdalic */
/*CPP_OPART mixfuncs */
/*CPP_OPART testrng */
/*CPP_OPART rngfuncs */
/*CPP_OPART rptvir */
/*CPP_OPART browse */
/*CPP_OPART utlmst */
/*CPP_OPART mtnfuncs */
/*CPP_OPART filewdgt */
/*CPP_OPART import */
/*CPP_OPART nrdlist */
/*CPP_OPART nrdlstr */
/*CPP_OPART nonlfld */
/*CPP_OPART warndlg */
/*CPP_OPART diagscrn */
/*CPP_OPART finfuncs */
/*CPP_OPART purfuncs */
/*CPP_OPART posfuncs */
/*CPP_OPART rlstfunc */
/*CPP_OPART gcyear */
/*CPP_OPART loadval */
/*CPP_OPART quitvfy */
/*CPP_OPART virfld */
/*CPP_OPART virfld2 */
/*CPP_OPART xsetup */
/*CPP_OPART payfuncs */
/*CPP_OPART appfuncs */
/*CPP_OPART prevnxt */
/*CPP_OPART miscbill */
/*CPP_OPART venfuncs */
/*CPP_OPART prtbrow */
/*CPP_OPART purstp1 */
/*CPP_OPART mtnwrt */
/*CPP_OPART mknrd */
/*CPP_OPART doheader */
/*CPP_OPART prtfnc */
/*CPP_OPART prtrng */
/*CPP_OPART supreq */
/*CPP_OPART mixsqlfuncs */
